// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0bpU8QjpwkJPWXBN5vlPm92-k7hMvC9I',
    appId: '1:212394802628:web:d26b86c3a5b902d2f87891',
    messagingSenderId: '212394802628',
    projectId: 'seekhere-508fb',
    authDomain: 'seekhere-508fb.firebaseapp.com',
    databaseURL: 'https://seekhere-508fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seekhere-508fb.firebasestorage.app',
    measurementId: 'G-9ZLRF6X9X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA747pJOrqNSWpXOPOaCIksYKeWQIHiTMQ',
    appId: '1:212394802628:android:c0a43231c2be6f34f87891',
    messagingSenderId: '212394802628',
    projectId: 'seekhere-508fb',
    databaseURL: 'https://seekhere-508fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seekhere-508fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOGXJ-lBf41DgTAbQwpAuwNtj1lmji6b0',
    appId: '1:212394802628:ios:4060fdec60fc5df4f87891',
    messagingSenderId: '212394802628',
    projectId: 'seekhere-508fb',
    databaseURL: 'https://seekhere-508fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seekhere-508fb.firebasestorage.app',
    iosBundleId: 'com.example.seekhereProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOGXJ-lBf41DgTAbQwpAuwNtj1lmji6b0',
    appId: '1:212394802628:ios:4060fdec60fc5df4f87891',
    messagingSenderId: '212394802628',
    projectId: 'seekhere-508fb',
    databaseURL: 'https://seekhere-508fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seekhere-508fb.firebasestorage.app',
    iosBundleId: 'com.example.seekhereProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0bpU8QjpwkJPWXBN5vlPm92-k7hMvC9I',
    appId: '1:212394802628:web:f5321140f7f5243ef87891',
    messagingSenderId: '212394802628',
    projectId: 'seekhere-508fb',
    authDomain: 'seekhere-508fb.firebaseapp.com',
    databaseURL: 'https://seekhere-508fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seekhere-508fb.firebasestorage.app',
    measurementId: 'G-CD4BVX23K6',
  );

}